#include "libby.h"

s_node  *create_game2(u_node *user)
{
  s_node  *start;
  s_node  *current;
  //s_node  *back;

  start = create_snode("--checkpoint--\nHaah, the beautiful lands of Aengor. Nothing more beautiful than that, truly.\nExcept maybe sweet potato cake.");
  start->choose_one = "east";
  start->choose_two = "west";
  start->option2 = create_snode("'The Still Lake'.\nLives up to its name, I suppose. What say you, u_name ? Up for a swim ?");
  start->option2->back = start;
  user->checkpoint = start;
  start->option1 = create_snode("'The Mystery Forest', huh ?\nThey say this place is crawling with all kinds of creatures - real dangerous stuff. Personally ? I'm pretty sure that's just what we tell the kids so they'll stop getting lost in there.\nIt's a damn maze, is what it is.");
  start->option1->back = start;
  current = start->option1;
  current->choose_one = "sign";
  current->choose_two = "enter";
  current->option1 = create_snode("Huh. You're right, there is something there, on the back. An engraving - it's a lute, I think ? Some kind of string instrument.");
  current->option1->back = current;
  current->option2 = create_snode("It's beautiful, u_name.\nSunlight streaming through the leaves, green as far as the eye can see... Careful, the roots !\nWhew. I think you'd better sick close to me.\nWhere are we going again ?");
  current->option2->back = current;
  current = current->option2;
  current->choose_one = "left";
  current->choose_two = "right";
  current->option1 = create_snode("The path is getting dangerous, u_name. You sure you want to keep going ?");
  current->option1->back = current;
  current->option1->choose_one = "forward";
  current->option1->option1 = create_snode("Seriously, u_name. The ground is more water than mud at this point, and I know you can't see it, but this fog ?\nI can barely see anything ! Can't lead you, if I'm blind too, you know ?");
  current->option1->option1->back = current;
  current->option1->option1->choose_one = "forward";
  current->option1->option1->option1 = create_snode("Damn it, u_name ! I told you we should have stopped.\nUgh. I'm not a medic, you know ? Here, sit down for a minute.");
  current->option1->option1->option1->damage = 5;
  current->option1->option1->option1->damage_msg = "|| Your foot got stuck in the mud and you've sprained your ankle. You've lost 5hp.";
  current->option1->option1->option1->back = current;
  current->option1->option1->option1->choose_one = "forward";
  current->option1->option1->option1->option1 = create_snode("Dude, come on.\nReally ?\nLike really - you're sure ?");
  current->option1->option1->option1->option1->back = current;
  current->option1->option1->option1->option1->choose_one = "forward";
  current->option1->option1->option1->option1->option1 = create_snode("There ! You happy ? We're stranded, lost in the middle of nowhere, drenched to the bone, both blind - one of us limping, for god's sake! - and still, still !\nWait, is that... ?\nThere's a light somewhere ahead. Not too far - couple meters maybe ? Looks like someone's holding it.\nWhat do we do, captain ?");
  current->option1->option1->option1->option1->option1->locked = 2;
  current->option1->option1->option1->option1->option1->option1 = create_snode("Why are you - ? You really think now is the time to start learning a new instrument ?\nOh. Oh, they're approaching ! How did you.. ?\nNevermind. Hi there !\nThey look old, u_name. White hair, long cloak... very mage-like.\nHi ! I'm Leon, this is u_name. They're injured. Can you help ?");
  current->option1->option1->option1->option1->option1->option1->back = current->option1->option1->option1->option1->option1;
  current->option1->option1->option1->option1->option1->back = current;
  current = current->option1->option1->option1->option1->option1;
  current->choose_two = "call out";
  current->option2 = create_snode("Alright.\nHey, you ! Stranger with the light ! We're kind of stranded, and my friend is hurt. Could you help us ?\nAaaaaand they're leaving. Of course.\nCan we please go now ?!");
  current->option2->back = start->option1->option2;
  current = start->option1->option2;
  current->option2 = create_snode("Looks like the path stops here. There's a sign here in a language I don't speak, a garden full of very weird-looking flowers, and a - what's that, a rat ?");
  current->option2->locked_desc = "Alright. Illegible sign, weird-looking house, and a rabbit.";
  current->option2->back = current;
  current = current->option2;
  current->choose_one = "rabbit";
  current->option1 = create_snode("How'd you even know that ?\nYou heard it ?\n...\n..\nOkay. Weirdo.\nAnyway, that's it. ");
  current->option1->back = current;
  current->option1->unlocks = current;
  current->choose_two = "house";
  current->option2 = create_snode("Dude, please don't make me knock on this stranger's door.\nYou sure ? Thanks, man, I appreciate it. Here, just... A little higher ?\n Yeah, there you go.");
  current->option2->choose_one = "knock";
  current->option2->back = start->option1->option2->option2;
  current->option2->option1 = create_snode("'Go away!'\n...\nAlright. I think maybe they want us to leave, u_name.");
  current->option2->option1->back = current;
  current = current->option2->option1;
  current->locked = 1;
  user->obj_names[0] = "hedgehog";
  current->option1 = create_snode("We have a... hedgehog for you here ?\n'A hedgehog...?\nMy Marjorie ! Oh, how I've missed you, darling - where did you find her ?'\nWell -\n'Doesn't matter. Come in, come in !'");
  current->option1->desc_obj = "\n'Here's something for you, sweethearts. A little thank you gift, so to speak.'";
  current->option1->choose_obj = "small lyre";
  current->option1->obj = 2;
  current->option1->back = start->option1->option2->option2;
  user->obj_names[1] = "small lyre";
  current = start->option2;
  current->choose_one = "forward";
  current->option1 = create_snode("I used to love swimming, you know. Something about the water holding you afloat, all that. Mmh ?\nWhy'd I stop ?\nWell, that's - that's a story for another time, u_name. How about we focus on the road, mmh ?");
  current->option1->desc_obj = " Like... over there, a hedgehog !";
  current->option1->back = current;
  current->choose_two = "swim";
  current->option2 = create_snode("Feels great, right ?\nYou can say I'm right, you know. Won't kill you or anything. No ? Nothing ?\nAlright.");
  current->option2->back = current;
  current->option2->damage = -3;
  current->option2->damage_msg = "|| The water feels wonderful. Very calming.\n|| You regain 3hp.";
  current = current->option1;
  current->obj = 1;
  current->choose_obj = "hedgehog";
  return (start);
}
